security:
    providers:
        in_memory:
            memory: ~

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            anonymous: true
            stateless: true
            guard:
                authenticators:
                  - 'yearlyapi.security.tokenauthenticator'
        main:
            anonymous: true
            form_login:
                login_path: /admin/login
                check_path: /admin/login
            logout:
                path: /logout
                target: /

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER }
